## Google Cloud Build - Build and Push Docker image

steps:

- id: Build image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME','-f','Dockerfile','.']

- id: 'Test Build: Download source'
  name: 'gcr.io/cloud-builders/wget'
  args: ['-O','test.zip','https://code.quarkus.io/d?g=org.acme&a=code-with-quarkus&v=1.0.0-SNAPSHOT&b=MAVEN&s=&cn=code.quarkus.io']

- id: 'Test Build: Unpack source'
  name: 'gcr.io/$PROJECT_ID/unzip'
  args: ['-q','-u','test.zip','-d','testbuild']

- id: 'Test Build: Change folder permissions'
  name: 'busybox'
  entrypoint: sh
  args: ['-c','chmod -R 777 /workspace/testbuild']

- id: 'Test Build: Build using newly created image'
  name: 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME'
  entrypoint: mvn
  args: ['clean','package','-Pnative','-f','testbuild/code-with-quarkus/pom.xml']

images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME']
  
options:
  machineType: 'N1_HIGHCPU_8'
  
timeout: 900s
