## Google Cloud Build - Build and Push Docker image

steps:

- id: Build image for root user
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA-root','-f','Dockerfile-root','.']
  
- id: Push image for root user
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA-root']

- id: Build image for mvn user
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA-mvn','-f','Dockerfile','.']
  
- id: Push image for mvn user
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA-mvn']
  
timeout: 600s
