## Google Cloud Build - Build and Push Docker image

steps:

- id: 'Test Build: Download source'
  name: 'gcr.io/cloud-builders/wget'
  args: ['-O','test.zip','https://code.quarkus.io/d?g=org.acme&a=code-with-quarkus&v=1.0.0-SNAPSHOT&b=MAVEN&s=&cn=code.quarkus.io']

- id: 'Test Build: Unpack source'
  name: 'gcr.io/$PROJECT_ID/tar'
  args: ['-tzvf','test.zip']

- id: Download latest image
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull','gcr.io/$PROJECT_ID/$REPO_NAME:latest']

- id: Build image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME','-f','Dockerfile','.']
  
- id: Push image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME']
  
- id: Tag as latest
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag','gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME','gcr.io/$PROJECT_ID/$REPO_NAME:latest']
  
- id: Push latest image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/$REPO_NAME:latest']
  
timeout: 600s
