## Google Cloud Build - Build and Push Docker image

steps:

- id: Download latest image
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull','gcr.io/$PROJECT_ID/$REPO_NAME:latest']

- id: Build image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA','-f','Dockerfile','.']
  
- id: Push image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']
  
#- id: Tag as latest
#  name: 'gcr.io/cloud-builders/docker'
#  args: ['tag','gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA','gcr.io/$PROJECT_ID/$REPO_NAME:latest']
  
#- id: Push latest image
#  name: 'gcr.io/cloud-builders/docker'
#  args: ['push','gcr.io/$PROJECT_ID/$REPO_NAME:latest']
  
timeout: 600s
