# Updated using documentation available via https://github.com/docker/build-push-action

name: Docker Build and Push
on:
  workflow_dispatch:
  release:
    types:
     - published
    tags:
     - 'v*'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log into Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Print workspace path
      run: echo $GITHUB_WORKSPACE && pwd && echo ${{github.ref}}
    - name: Build and Push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jthambly/graalvm-mvn:latest

  build-root:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Strip user information
      run:  sed -z 's/# Run as new user.*\n\n#/#/' Dockerfile > Dockerfile-root
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log into Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Print workspace path
      run: echo $GITHUB_WORKSPACE && pwd && echo ${{github.ref}}
    - name: Build and Push image
      uses: docker/build-push-action@v2
      with:
        push: true
        file: Dockerfile-root
        tags: jthambly/graalvm-mvn:rootusr