# Updated using documentation available via https://github.com/docker/build-push-action
# Updated using documentation available via https://github.com/crazy-max/ghaction-docker-meta

name: Docker Build and Push
on:
  pull_request:
    branches:
     - master
    types: [opened, synchronize]
  push:
    branches:
     - master
    tags:
     - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: jthambly/graalvm-mvn
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log into Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}