name: Docker Build and Push
on:
  pull_request:
    types:
     - opened
     - synchronize
    branches:
     - master
  push:
    branches:
     - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker latest image
      uses: docker/build-push-action@v1
      with:
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: jthambly/graalvm-mvn
        tags: "$GITHUB_REF"