# Updated using documentation available via https://github.com/docker/build-push-action

name: Docker Build and Push
on:
  pull_request:
    types:
     - opened
     - synchronize
    branches:
     - master
  push:
    branches:
     - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log into Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          jthambly/graalvm-mvn:latest
          "jthambly/graalvm-mvn:${{GITHUB_REF}}"